version: "3.8"

services:
  admin_panel:
    container_name: hotel-elmiriam-admin-panel
    image: ranckosolutionsinc/hotel-elmiriam-admin-panel:v1.0
    # build: ./
    restart: always
    # environment:
    #   - PORT=5000
    # env_file:
    #   - ./src/.env
    ports:
      - "3000:3000"
    networks:
      - hotel-elmiriam-network
    labels:
      - "traefik.http.routers.admin_panel.rule=Host(`admin.hotel-elmariam.localhost`)"  
      - "traefik.http.services.admin_panel.loadbalancer.server.port=3000"
    # depends_on:
    #   - mongo

networks:
  hotel-elmiriam-network:
    name: hotel-elmiriam
    driver: bridge
    external: true  
