services:
  user_panel:
    container_name: hotel-elmiriam-user-panel
    image: ranckosolutionsinc/hotel-elmiriam-user-panel:v1.0.0
    # build: ./
    restart: always
    # environment:
    #   - PORT=5000
    # env_file:
    #   - ./src/.env
    ports:
      - "5000:5000"
    networks:
      - hotel-elmiriam-network
    labels:
      - "traefik.http.routers.user_panel.rule=Host(`user-panel.rancko.labs`)"
      - "traefik.http.services.user_panel.loadbalancer.server.port=5000"
    # depends_on:
    #   - reverse-proxy

networks:
  hotel-elmiriam-network:
    name: hotel-elmiriam
    driver: bridge
    external: true
